baseURL = "https://1pedro.github.io/blog"
languageCode = "en-us"
title = "Pedro"
theme = "hugo-tania"
author = "1pedro"
paginate = 2
enableEmoji = true
enableRobotsTXT = true
removePathAccents = true
timezone = "America/Bahia"
siteDesc = "teste"
pluralizeListTitles = false
[params]
    titleLogo = 'favicon.ico'
    enableFootnotes = true

    [params.socialOptions]
    github = "https://github.com/1pedro"

    [params.colorScheme]
        default = 'dark'

[menu]
    [[menu.header]]
        name = 'Til'
        identifier = 'Today I Learned'
        url = '/today i learned'
        pre = 'ðŸ§  '


[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]