baseURL = "https://1pedro.dev"
languageCode = "en-us"
title = "1pedro"
theme = "hugo-tania"
author = "1pedro"
enableEmoji = true
enableRobotsTXT = true
removePathAccents = true
timezone = "America/Bahia"
siteDesc = "Blogging and learning one post at time."
pluralizeListTitles = false

[pagination]
    pagerSize=10

[params]
    titleLogo = 'favicon.ico'
    enableFootnotes = true

    [params.socialOptions]
    github = "https://github.com/1pedro"

    [params.colorScheme]
        default = 'dark'

    
    [params.comments]
      enabled = true
      provider = "giscus"

      [params.comments.giscus]
        repo = "1pedro/blog"
        id = "R_kgDOHEyONQ"
        mapping = "pathname"
        
        [params.comments.giscus.category]
        id = "DIC_kwDOHEyONc4COS-e"
        name = "Announcements"
        loading = "lazy"
        lang = "en"



[menu]

    [[menu.header]]
        name = 'Resume'
        identifier = 'cv'
        pre = 'ðŸ§¾ '
        url = '/cv.pdf'

    [[menu.header]]
        name = 'Til'
        identifier = 'Today I Learned'
        url = 'today-i-learned'
        pre = 'ðŸ§  '
        
    [[menu.header]]
        name = 'Clojure'
        identifier = 'clojure'
        url = 'clojure'
        pre = '<img style="width:25px;height:25px;vertical-align: sub;" src="https://clojure.org/images/clojure-logo-120b.png"/>&nbsp;'



[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
